### PR TITLE
Support encoding resolution choice for dynamic MP4 or WebM videos (AVideo Encoder v3.7)

### PR DESCRIPTION
**Pull request by sizious**
This PR add the possibility to choose the encoding resolutions used when uploading a Dynamic MP4 or WebM video.

This can be useful in case of you don't want to waste time for encoding your videos in all the resolutions supported by AVideo.

At least one resolution must be selected and AVideo Encoder will check for that. By default, all the resolutions are selected.

This option is only supported for Dynamic MP4 or Dynamic WebM.

**Note:** This passes AVideo Encoder to the `3.7` version. If the instance isn't updated, then this option will be disabled, and all resolutions will be considered to be selected.

dynamic-video-resolution-setting-support

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
Awesome, is that for automatic resolutions?
why  not also HLS?

**Comment by sizious** [comment]
Ola @DanielnetoDotCom,

The whole purpose of these changes are focused of the `getDynamicCommandFromFormat()` method that is used when uploading a MP4 or WebM video. I was planning to support HLS too, as you might see in the code, I started to use it and I added a `TODO` comment. The thing is... I don't know how the HLS videos works to be honest! So I wasn't able to update the HLS method. Sorry for this.

**Comment by sizious** [comment]
Oh OK, I've just saw that HLS videos stand for Live Stream. I never tried to use the Live Stream feature of AVideo.
So I guess that the `preProcessDynamicHLS()` method should be improved in the same way of the `getDynamicCommandFromFormat()` method, but I don't know how the Live Stream feature actually works.

**Comment by DanielnetoDotCom** [comment]
Hi, it is not for Livestream, but do not worry, I will review this code, and make it work for HLS as well.

also, I didn't see the installation modification to add this new database field.

thanks for your help

**Comment by sizious** [comment]
Oh, OK sorry, I don't know AVideo in deep; as you noticed, I'm submitting changes only if I know exactly what I'm doing!

I've added a v`3.7` script, and in my dev instance it's seems to be enough for upgrading the DB, i.e. adding the `resolutions` field to the `configurations` table. Is there something else to modify?

And I just want to say, thank you for your product, you really did a great job. Thank you for this!

**Comment by sizious** [comment]
Thank you very much for finishing this feature!

**Comment by DanielnetoDotCom** [comment]
Thank you for the support

**Pull request merged**
