### PR TITLE
-c copy and -preset can't be on same line

### PR DESCRIPTION
**Pull request by akhilleusuggo**
I'm not sure Daniel this line means , but if what it does is to generate the tmp file , then `-c copy -movflags +faststart` only. If not , this is the right command line then.

### CODE REVIEW

**Comment by akhilleusuggo** [comment]
#371

**Comment by DanielnetoDotCom** [comment]
I mean with this line is to copy the original resolution without the need to resize that. 

I mean I want to encode the highest resolution the fast as possible. 

what do you think?

**Comment by akhilleusuggo** [comment]
You can't. You can just copy. But if the file codec is not supported on HTML5 , will fail .

**Comment by akhilleusuggo** [comment]
This is the only way , maybe with `-strict -2` for some unsupported , maybe I should include it , I had issues with restream because didn't include -strict -2

**Comment by DanielnetoDotCom** [comment]
Thanks, @akhilleusuggo for sharing your knowledge

**Comment by akhilleusuggo** [comment]
Ok, you trolling me now... :(

**Comment by DanielnetoDotCom** [comment]
> Ok, you trolling me now... :(

No, I am not, I am really grateful. definitely, you know more about FFMPEG than I.

**Pull request merged**
