### PR TITLE
changed JS scripts to cloudflare

### PR DESCRIPTION
**Pull request by ronaldod**
To make the website smaller it and quicker it can be useful to use the CDN from cloudflare.

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
I like this, but the problem is... if I install this site in an environment without the internet?

for example if I want to have a video site in some internal network?
maybe this can be optional, and set in the customizeAdvanced plugin

**Comment by ronaldod** [comment]
The thing your whole site is depended on the internet. So many links to JS scripts in CDN's around the world. That means you need to add them all in your source or go for CDN. At the moment it is mixed.
And please use relative paths if you include the,. Not absolute. That will help a lot with servers behind a nat router or reverse proxy.

**Comment by DanielnetoDotCom** [comment]
Hi

a relative path will be a problem, we add the scripts on header and footer include file, and it cannot be relative, due we include it in many different directory levels.

But use CDN can be an option, but We must create a way to deactivate it and use a local file. 

I currently have users that uses this project to show videos in remote places without the internet.

I agree, maybe some resources will not work, but the main features here will work with no problem.

**Comment by ronaldod** [comment]
You can do relative from the root. Not only relative from where you are now .
[www3 linkages](https://www.w3schools.com/html/html_filepaths.asp)
So by not using like `../js/form.php`  you do  `/view/js/form.php` you still can resolve your problem. If understand your issue correctly.

**Comment by DanielnetoDotCom** [comment]
I know, but some times the user install the code inside a subfolder, and the relative from root will not work

for example the site installed on `https://mydomain.com/streamersite/` will not work

**Comment by ronaldod** [comment]
Now i understand the cause of your concern. So there should be a variable with that path name inserted instead of the full domain path.  So instead of ` $global['webSiteRootURL']; ?>` . 

You should be able to create sub version like ` $global['webSiteRootpath']; ?>`  that only contains `/streamersite`

Is that an option ?

**Comment by DanielnetoDotCom** [comment]
Yes, this is a good option. $global['webSiteRootPath']

But I will need to release an update for it.

**Comment by ronaldod** [comment]
Yes i think solution would work great also for implementation with reverse proxy and who are not aware how they in a nat environment. 

Like i host everything behind HA proxy That works great but as soon your want to use nat or have docker installations your going to run into trouble. 

Looking forward to test some example code.

**Comment by DanielnetoDotCom** [comment]
I just sent an update where you may have the $global['webSiteRootPath'] from the configuration.php file

**Comment by ronaldod** [comment]
I'm going for the new fix will close this request

**Comment by ronaldod** [comment]
I do not see your commits back. What am i missing ?

**Comment by DanielnetoDotCom** [comment]
There is a commit.

It will modify the configuration.php file

**Comment by ronaldod** [comment]
confused :
image

I do not see those to the encoder repository. Maybe i need to dive into some github manuals.

**Comment by DanielnetoDotCom** [comment]
OMG, I see, I only submit it to the Streamer.

I will submit an encoder update later.

**Comment by ronaldod** [comment]
Can you do the submit ? The i can go fix things for the docker installation

**Comment by DanielnetoDotCom** [comment]
Sorry for the late replay, I guess it is correct now, please confirm, you should have the $global['webSiteRootPath'] variable

**Comment by DanielnetoDotCom** [comment]
Also, there is a JS variable so you can use in case you need

image

**Comment by DanielnetoDotCom** [comment]
Hi

will you replace the paths to the $global['webSiteRootPath']?

of do you think the CDN is a better idea?

**Comment by ronaldod** [comment]
I will close this pull and open an enhancement issue as it the path is now to go on self hosted files and not a CDN. In the future there need to be a statement where to host all common js/CSS files. Local or CDN and not mixed set. That gives confusion. Of course the Avideo based files must hosted locally. And best is to find one reliable CDN that host those files.

Cloudflare is a good one.
Just need to put all pros and cons together.

- CDN

PRO
1. Faster global access and faster site load time.
2. Easy to maintain and less files/data in repository.

CON
1. If hosted internally company's need to open firewall for the files.
2. Need to choose a reliable CDN

**Pull request closed without merging**
